"""empty message

Revision ID: 03c73ce9d935
Revises: 8882fa6660b2
Create Date: 2018-10-17 17:55:08.274241

"""
from alembic import op
import sqlalchemy as sa
import auth.models


# revision identifiers, used by Alembic.
revision = '03c73ce9d935'
down_revision = '8882fa6660b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
