"""empty message

Revision ID: 8882fa6660b2
Revises: cdb2deb04b2a
Create Date: 2018-10-17 15:39:38.544237

"""
from alembic import op
import sqlalchemy as sa
import auth.models


# revision identifiers, used by Alembic.
revision = '8882fa6660b2'
down_revision = 'cdb2deb04b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.Unicode(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
